### ISSUE TITLE
"Unable to retrieve clip information (2)" error when trying to export a clip as a video file

### ISSUE THREAD

**Issue by Bloodsnake** [flathub/com.valvesoftware.Steam#1366]
Hello, I am using the newest version of flatpak and the steam flatpak on fedora 41.

When I record a video in the background while playing and then want to clip some part of it I get the error above when trying to export it. [This thread](https://steamcommunity.com/groups/SteamClientBeta/discussions/3/4840897626277132067/) in the steam forums describes my observed behaviour pretty well. The recording, editing and "create a share link" option works well for me.

**Comment by Spaceslug** [comment]
I have same issue as @Bloodsnake. I use Steam flatpak on Arch.

**Comment by losuler** [comment]
As suspected by https://github.com/ValveSoftware/steam-for-linux/issues/11433#issuecomment-2464833253, I rolled back the Steam Flatpak one version (which is using org.freedesktop.Platform 23.08 and not 24.08), and now exporting clips works:

```
 flatpak update --commit=173cd565d98d4951bd858bad290e8481a9e72dbf5f7c9c980165a060666184b1 com.valvesoftware.Steam
```

**Comment by bigimattia** [comment]
Same issue on fedora 41. Game record seems to work. Clips shortuct plays a sound but doesn't get saved

**Comment by TarsiSurdi** [comment]
Updating Steam to the latest Beta version release on [November 25th](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/4489620901087676801) didn't help with this issue.

**Comment by helix26j** [comment]
Could this be related to the 23.08-extra that was available in 23.08 but not in 24.08?  It looks like the freedesktop runtime messed up the naming and 24.08 is called 24.08extra without the dash.
```
Freedesktop SDK	org.freedesktop.Platform.GL.default	24.2.5	23.08	system
Freedesktop SDK	org.freedesktop.Platform.GL.default	24.2.5	23.08-extra	system
Freedesktop SDK	org.freedesktop.Platform.GL.default	24.2.7	24.08	system
Freedesktop SDK	org.freedesktop.Platform.GL.default	24.2.7	24.08extra	system
```

I only see it referenced under Platform.GL32 in Steam's metadata:
versions=24.08;24.08-extra;1.4

I am not that familiar with flatpaks to know if this could be an issue as I haven't experienced any gaming issues.  I don't know if there is any way to test overriding settings under Extensions.

Steam's streaming_log reports an error regarding initializing hardware accel, even if hardware accel is turned off for recording.
[2024-11-28 08:48:22][2944.347692] libav: No support for codec h264 profile 100. initialisation returned error.
[2024-11-28 08:48:22][2944.347718] libav: Failed setup for format vaapi: hwaccel initialisation returned error.

Steam is reporting what looks like a normal version of mesa:
Driver Version: 4.6 (Compatibility Profile) Mesa 24.2.7 (git-3900828265)

**Comment by imraven** [comment]
this was broken for me in ubuntu/flatpak but the latest version of com.valvesoftware.Steam (1.0.0.81) has fixed it.

**Comment by Bloodsnake** [comment]
Closing the issue since it works now. Thanks for all the work!

**Comment by TarsiSurdi** [comment]
I'm not sure if this is the same issue, but even after updating to `1.0.0.81` this problem has not been fixed for me...

https://github.com/ValveSoftware/steam-for-linux/issues/11433#issuecomment-2558718742

**Comment by AetherCollective** [comment]
On windows, this is still an issue for me

**Comment by just-Bri** [comment]
Why was this issue closed?
This is still an ongoing issue on multiple operating systems and multiple versions of steam.

Currently running in to this issue on stable and beta steam channels on NixOS.
Current errir us "(2)" whatever that means.

Interesting find: when I try to specify the output file the dialog opens my file browser and shows an immediate error "Cannot find..." the file. Yea, because it doesn't exist and I'm trying to create it via the export.

Something wonky def going on under the hood.

**Comment by Bloodsnake** [comment]
> Why was this issue closed?
> This is still an ongoing issue on multiple operating systems and multiple versions of steam.

Multiple people (including myself) reported that it has been fixed in the flatpak version. This is the flatpak steam bug tracker and since it seemingly doesn't effect the flatpak version anymore it is closed here. This project is (I think) independent of valve. Please open an issue on the [steam github repo](https://github.com/ValveSoftware/steam-for-linux) if you have an issue with one of the versions valve distributes.

**Comment by TarsiSurdi** [comment]
> Multiple people (including myself) reported that it has been fixed in the flatpak version. This is the flatpak steam bug tracker and since it seemingly doesn't effect the flatpak version anymore it is closed here. This project is (I think) independent of valve. Please open an issue on the [steam github repo](https://github.com/ValveSoftware/steam-for-linux) if you have an issue with one of the versions valve distributes.

I think it would be best for you to re-open this issue since it is still present on both the regular Steam release and by consequence of that, your Flatpak version, even if it's not affecting as many people now, it seems. 

When replying to this thread earlier I linked to an issue from Valve's issue tracker, but would like you to know that I was referring to an issue with the Flatpak release all along in case it was ambiguous.

**Comment by basilioss** [comment]
I'm getting Unable to retrieve clip information (9) error, but exporting clips worked some time ago without any errors. Tried to install Steam from official Arch Linux repository and everything works fine now.
