### ISSUE TITLE
Rise of the Tombraider freezes

### ISSUE THREAD

**Issue by Tids** [flathub/com.valvesoftware.Steam#228]
**Game information**
Rise of the Tombraider

**Distribution name and version where applicable**
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	17.1.12
Codename:	Hakoila

**Flatpak info**
Flatpak 1.0.1
default
host

**Problem description**
RotT freezes after showing up vendor logos. 
![bildschirmfoto von 2018-09-14 15-00-59](https://user-images.githubusercontent.com/18744080/45551733-19c33f80-b82f-11e8-99bf-b9a10de70722.jpg)
After forced close Its not possible to restart the game, because now also the pre-game options only shows a black screen and is also frozen
![grafik](https://user-images.githubusercontent.com/18744080/45551785-3e1f1c00-b82f-11e8-9388-f2e3b38e4787.png)

**Does this issue reproduce with native Steam**
No. With native steam it rune just fine

**Comment by nanonyme** [comment]
Was this with or without big picture mode?

**Comment by Tids** [comment]
It was without BPM, but I have tried and its the same with BPM

**Comment by nanonyme** [comment]
I was asking because there's reports of same issue with BPM. Which GPU do you have?

**Comment by Tids** [comment]
It's a Radeon R9 380 with amdgpu driver

**Comment by Tids** [comment]
If i start the game in a window, not fullscreen, it will work, launches and runs just fine. Still this is the behavior only with the flatpak.

**Comment by Tids** [comment]
If i start the game in a window, not fullscreen, it will work, launches and runs just fine. Still this is the behavior only with the flatpak.

**Comment by nanonyme** [comment]
That's just so odd... which version of Mesa do you have on the host?

**Comment by nanonyme** [comment]
Does the shader cache fix that was just integrated affect this any?

**Comment by Tids** [comment]
on the host it's Mesa 18.2.1 

No. latest update of the flatpak and still the same issue here

**Comment by nanonyme** [comment]
There's now also Mesa 18.2.1 in the runtime. Any change?

**Comment by Tids** [comment]
tested and still is freezing when launched in fullscreen, running nice on windowed. 😭

**Comment by nanonyme** [comment]
Any change with latest runtime changes? :/

**Comment by Tids** [comment]
No change. It still freezes when launched in fullscreen; but works OK when in windowed mode

**Comment by demollom** [comment]
I can confirm this. Here is a snippet from the log.
[rott-log.txt](https://github.com/flathub/com.valvesoftware.Steam/files/2758746/rott-log.txt)

**Comment by leonardo2707** [comment]
I could not test here with flatpak steam version, but this problem occurs in the native steam-manjaro version too, and I discovered that this problem does not occur if I use Xorg instead of the wayland.

I just came to say that, maybe some game problem with the wayland I do not know.

**Comment by nanonyme** [comment]
There was a bug in runtime Vulkan support which was fixed in latest update. Might be worth updating and testing again.

**Comment by Tids** [comment]
Tried it just now with the latest whatever is available right now via `flatpak update`. It still freezes in fullscreen. Its the same on X11 and xwayland. It still works in window mode most of the time.

**Comment by winehub** [comment]
The group of fdo has fixed the vulkan problem. I nerveless have any problem with this manjaro. 
Here my two hardware specs:

iMac 2015 (manjaro) i7 4 GHZ  R9 M395.
i7 3770k, Ryzon 1950x RX 480 (flashed to 580).

flatpak --version -> 1.1.2
flathub mesa 18.3.1 includes the vulkan fix.

Try to uninstall the game org reset it to default (driver must show up messa 18.3.1 vulkan ).

I did try out after complete reinstall everything from flathub.

**Comment by Tids** [comment]
xorg-server 1.20.4 fixes this for me on wayland completely, on X11 i have to use the buildin modesettings driver, if I use xorgs-amdgpu it keeps freezing. So I dont think its a flatpak/flathub related bug, but (at least for me) x11/xf86-video-amdgpu related

**Comment by nanonyme** [comment]
So is the remaining thing a host-side issue?

**Comment by Tids** [comment]
Yes it was. It now also works again on X11 with amdgpu xorg driver. Sadly I cant tell what fixed it, but it works now just fine :+1: 
Thanks for your help in here!
